identification:
  USER_EMAIL : 'enter_your_LinkedIn_username'
  USER_PASSWORD : 'enter_your_LinkedIn_password'

filters:
  FINANCE : 'MARKET'
  ROLES : ['All']
  INSTITUTIONS : ['All']
  SENIORITIES : ['All']
  LOCATIONS : ['All']
